### ISSUE TITLE
EXPECT0 output going to stderr

### ISSUE THREAD

**Issue by flawmop** [Chaste/ApPredict#1]
When doing the following I seem to end up with wget output from [EXPECT0 ](https://github.com/Chaste/ApPredict/blob/master/src/lookup/LookupTableLoader.cpp#L479) going to _stderr_, whereas I'd have hoped for it to go to _stdout_.

```
--model 8 --pacing-freq 1.0 --pacing-max-time 5 --pic50-herg 1 --hill-herg 1 --saturation-herg 0 --pic50-spread-herg 0.21 --plasma-conc-high 100 --plasma-conc-low 0 --plasma-conc-count 4 --plasma-conc-logscale true  --credible-intervals 2> stderr
```

**Comment by flawmop** [comment]
Oops! Expected stderr to be just for errors (see [stderr](https://pubs.opengroup.org/onlinepubs/9699919799/functions/stdin.html)) but it's for diagnostic output.

**Comment by mirams** [comment]
Probably a *can't fix* then!
